/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class chapter12_HelloNative */

#ifndef _Included_chapter12_HelloNative
#define _Included_chapter12_HelloNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     chapter12_HelloNative
 * Method:    greeting
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_chapter12_HelloNative_greeting
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
