/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class chapter12_Employee */

#ifndef _Included_chapter12_Employee
#define _Included_chapter12_Employee
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     chapter12_Employee
 * Method:    raiseSalary
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_chapter12_Employee_raiseSalary
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
