/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class chapter12_Welcome */

#ifndef _Included_chapter12_Welcome
#define _Included_chapter12_Welcome
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
